[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "csud"
version = "0.1.0"
description = "Python Modules used at Coll√®ge du Sud for computer science teaching"
dependencies = ["matplotlib"]